# Generated by Django 4.2 on 2023-05-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamescore",
            name="game",
            field=models.TextField(
                choices=[("MATH", "Math Game"), ("ANAGRAM", "Anagram Game")],
                default="MATH",
            ),
        ),
    ]
